### ISSUE TITLE
Korrektur der Platine - sofern Updates geplant sind

### ISSUE THREAD

**Issue by UliD-zz** [wolwin/WW-myPCB#1]
R4 und C5 müssen sich eine Bohrung teilen. Für den Fall, dass ein Update geplant ist, könnte man diese Kleinigkeit beheben und eine zweite Bohrung einplanen.

**Comment by wolwin** [comment]
Du meinst sicherlich die Platine HB-UNI-Sens-X - oder?
Ja, das sollte eigentlich so sein - gleiches gilt auch für R2-C4-R3: Widerstand und Kondensator teilen sich eine Bohrung, Für 1/4 Watt Widerstände funktioniert das auch, aber bei 1/2 Watt Widerständen ist die Bohrung zu klein ...
Bei R4 und C5 wäre eine seperate Bohrung machbar - bei R2-C4-R3 müßte evtl. die Bohrung größer ausfallen.

Kannst Du bitte dazu einen pull request für HB-UNI-Sens-X aufmachen - Danke!

**Comment by UliD-zz** [comment]
Hallo Wolfram,

danke für die schnelle Rückmeldung.
Ja, HB-UNI-Sens-X ist richtig. 
Für mich brauche ich keine Korrektur, hab das Problemchen gelöst. Ich dachte nur, dass irrtümlich nur eine Bohrung vorhanden sei.
Mein Input war daher gedacht für eine eventuell geplante Neuauflage.

Werde daher vorerst keinen pull request eröffnen, vielleicht später, wenn ich dann doch noch mal Platinen selbst fertigen lassen will.

Also, nochmal danke für die schnelle Rückmeldung und ein schönes Wochenende.

Gruß
Uli

PS: Allgemeine Frage zum AskSin++: Kannst du eine Empfehlung aussprechen, wie am sinnigsten ein Einstieg in diese Thematik angegangen werden kann? 

Quellcode und Analyse von Klassen wäre für mich nicht die erste Wahl…

Bei fhem gibt’s eine Reihe von Wikis, die haben vor Jahren gute Dienste geleistet. Bei AskSin++ vermisse ich dies. Bin für Tipps dankbar.

**Comment by wolwin** [comment]
Hallo Uli,
Danke - werde das mit Deiner Anregung im Auge behalten, falls mal eine Platinenänderung anstehen sollte.

Zu den Asksin++ Grundlagen wurde eigentlich für einen Einstieg das Wesentliche unter [https://asksinpp.de/Grundlagen/](url) aufgezeigt. Anfangen sollte man aber definitiv mit 'einfachen' Dingen. Ein guter Anlaufpunkt sind noch die Github Seiten von Tom Major [https://github.com/TomMajor/SmartHome](url) und Jérôme [https://github.com/jp112sdl](url). Fragen kann man auch im FHZ Forum stellen [https://homematic-forum.de/forum/viewforum.php?f=76](url).
